language:
  ruby
services:
  docker
  
before_install:
  - docker-compose -f zabbix-compose.yml build
  - docker login --username magzim21 --password $DOCKER_PASSWORD
  # This will select newly created image amonng all images and push it to dockerhub
  - docker push $(docker images --format "{{.Repository}}" | grep '.*zabbix')


# Just another option for deploying:

# deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "zabbix-sql"
#   env: "ZabbixSql-env"
#   bucket_name: "elasticbeanstalk-eu-central-1-249446252531"
#   bucket_path: "zabbix-sql"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
